### ISSUE TITLE
Deleting an employee should display a delete confirmation prompt.

### ISSUE THREAD

**Issue by coasterboy101** [coasterboy101/Timesheet#8]
See title.

**Comment by coasterboy101** [comment]
On second thought, since we have the employed field, I might as well remove the ability to delete an employee. Jean, what do you think?

**Comment by coasterboy101** [comment]
I will go ahead and get rid of the delete button, if we decide that we still need it, we can roll back the changes.

**Comment by jeanhill72** [comment]
Why would you get rid of the delete button?  In the real world you would need it.  Just curious.

```
  From: Rory Ellis <notifications@github.com>
```

 To: coasterboy101/Timesheet Timesheet@noreply.github.com 
 Sent: Sunday, November 15, 2015 5:05 PM
 Subject: Re: [Timesheet] Deleting an employee should display a delete confirmation prompt. (#8)

I will go ahead and get rid of the delete button, if we decide that we still need it, we can roll back the changes.—

**Comment by jeanhill72** [comment]
Sorry I didn't get back to you sooner.  I think it should stay.  However, if you have removed it, we can leave it off since we are down to "crunch" time...

```
  From: Rory Ellis <notifications@github.com>
```

 To: coasterboy101/Timesheet Timesheet@noreply.github.com 
 Sent: Sunday, November 15, 2015 3:44 PM
 Subject: Re: [Timesheet] Deleting an employee should display a delete confirmation prompt. (#8)

On second thought, since we have the employed field, I might as well remove the ability to delete an employee. Jean, what do you think?—

**Comment by coasterboy101** [comment]
Well, I was thinking that the user would just uncheck the Employed
checkbox, rather than delete an employee, which would create a lot of
orphaned data.

**Comment by coasterboy101** [comment]
Also, all I did was set the button's IsVisible property to false. None of the code has been removed.

**Comment by jeanhill72** [comment]
We can leave it.

```
  From: Rory Ellis <notifications@github.com>
```

 To: coasterboy101/Timesheet Timesheet@noreply.github.com 
Cc: jeanhill72 jeanhill72@yahoo.com 
 Sent: Sunday, November 15, 2015 5:57 PM
 Subject: Re: [Timesheet] Deleting an employee should display a delete confirmation prompt. (#8)

Also, all I did was set the button's IsVisible property to false. None of the code has been removed.—
